version: '2.4'

services:
  pbm:
    build:
      context: .
      target: ${NODE_ENV}
      args:
        - NODE_ENV=${NODE_ENV}
    ports:
      - "8000:${SERVER_PORT}"
    volumes:
      - .:/app:delegated
      - /app/node_modules