[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy-Report-Only = "default-src 'none'; report-uri /csp-violation"
    Referrer-Policy = "strict-origin-when-cross-origin"
