[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
    for = "/vishnu-paath-uk-prayer-book.pdf"
    [headers.values]
      Content-Disposition = "attachment"

[build]
  command = "npm run build"
  publish = "public"
  Functions = "src/functions"

[build.environment]
  # cache Cypress binary in local "node_modules" folder
  # so Netlify caches it
  CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
  # set TERM variable for terminal output
  TERM = "xterm"

[[plugins]]
  package = "netlify-plugin-cypress"
    [plugins.inputs]
    record = true
